apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserve
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
    volumes:
    - name: test-volume
      gcePersistentDisk:
        pdName: my-data-disk
        fsType: ext4
